name: 'Conversational release action'
description: 'Release Quarkus by conversing with a GitHub Action'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  action:
    description: 'Name of the action (if named)'
    required: false
  interaction-comment:
    description: 'Optional interaction comment'
    required: false
outputs:
  branch:
    value: ${{ steps.action.outputs.branch }}
  qualifier:
    value: ${{ steps.action.outputs.qualifier }}
  major:
    value: ${{ steps.action.outputs.major }}
  version:
    value: ${{ steps.action.outputs.version }}
  jdk:
    value: ${{ steps.action.outputs.jdk }}
  origin-branch:
    value: ${{ steps.action.outputs.origin-branch }}
  status:
    value: ${{ steps.action.outputs.status }}
  current-step:
    value: ${{ steps.action.outputs.current-step }}
  current-step-status:
    value: ${{ steps.action.outputs.current-step-status }}
  workflow-run-id:
    value: ${{ steps.action.outputs.workflow-run-id }}
  interaction-comment:
    value: ${{ steps.action.outputs.interaction-comment }}
runs:
  using: "composite"
  steps:
    - name: Inject quarkus-github-action repository credentials
      shell: bash
      run: |
        if [ -f ~/.m2/settings.xml ]; then
          if ! grep -q '<id>quarkus-github-action</id>' ~/.m2/settings.xml; then
            sed -i.bak 's@</servers>@<server><id>quarkus-github-action</id><username>${env.GITHUB_ACTOR}</username><password>${env.GITHUB_TOKEN}</password></server></servers>@' ~/.m2/settings.xml
          fi
        else
          mkdir -p ~/.m2/
          cat <<\EOF > ~/.m2/settings.xml
        <?xml version="1.0"?>
        <settings>
          <servers>
            <server>
              <id>quarkus-github-action</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
        fi
    - name: Set up JBang
      uses: jbangdev/setup-jbang@main
    - name: Run the action
      id: action
      run: |
        echo "Java 21: ${JAVA_HOME_21_X64}"
        if [[ -n "${JAVA_HOME_21_X64}" ]]; then
          echo "Installing ${JAVA_HOME_21_X64} as JDK 21 for JBang"
          jbang --verbose jdk install 21 ${JAVA_HOME_21_X64}
        fi
        jbang --java 21 --fresh --repos 'quarkus-github-action=https://maven.pkg.github.com/quarkusio/conversational-release-action/' --repos 'mavencentral' io.quarkus.bot:conversational-release-action:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
